application: singlecalendar
version: 1
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- mail

handlers:
- url: /stylesheets
  static_dir: stylesheets
 
- url: /javascript
  static_dir: javascript
      
- url: /.*
  script: singlecal.app

- url: /_ah/mail/.+
  script: singlecal.app
  login: admin

libraries:
- name: jinja2
  version: latest

